### ISSUE TITLE
SQLDataQueue should properly handle db failures

### ISSUE THREAD

**Issue by praveek** [adobe/aepsdk-core-android#57]
#### Current behavior
SQLDataQueue currently closes the underlying database in case of an exception. 
The exception is handled and debug log messages are logged, but subsequent operations fail and the db is unrecoverable during current session.

#### Expected behavior
Recreate the DB incase of unrecoverable errors to avoid data loss and elevate log level to warning/error when appropriate. 

#### Logs taken while reproducing problem
<details>
<summary>Logs from Edge test app</summary>
2022-04-21 10:16:05.637 21001-21051/com.adobe.marketing.edgetestapp D/AdobeExperienceSDK: ADBDatabase - insertRow - Error in inserting row into table (TB_AEP_DATA_ENTITY). Error: (Cannot open database '/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge': Directory /data/user/0/com.adobe.marketing.edgetestapp/cache doesn't exist)
2022-04-21 10:16:05.638 21001-21051/com.adobe.marketing.edgetestapp D/AdobeExperienceSDK: ADBDatabase - closeDatabase - Unable to close database, database passed is null.
2022-04-21 10:16:05.638 21001-21051/com.adobe.marketing.edgetestapp V/AdobeExperienceSDK: SQLiteDataQueue - add - Successfully added DataEntity (DataEntity{uniqueIdentifier='5509fb70-fe73-4722-a8c4-996f4d353d84', timeStamp=Thu Apr 21 10:16:05 PDT 2022, data={"event":{"type":"com.adobe.eventtype.edge","source":"com.adobe.eventsource.requestcontent","number":24,"name":"AEP Request Event","timestamp":1650561365457,"responsePairId":"7c5b8625-7ad4-4b6f-87be-9bd892f80713","data":{"xdm":{"eventType":"commerce.purchases","commerce":{"productListAdds":{"value":21},"purchases":{"value":1},"order":{"priceTotal":20,"currencyCode":"RON"}}},"datasetId":"abc"},"uuid":"5509fb70-fe73-4722-a8c4-996f4d353d84"},"configuration":{"edge.configId":"example","edge.domain":"example.data.adobedc.net"},"identityMap":{"identityMap":{"ECID":[{"id":"09867831920078526066116478502603050971","authenticatedState":"ambiguous","primary":false}]}}}}) to DataQueue
2022-04-21 10:16:05.641 21001-21054/com.adobe.marketing.edgetestapp E/SQLiteLog: (14) cannot open file at line 39583 of [bcd014c473]
2022-04-21 10:16:05.645 21001-21054/com.adobe.marketing.edgetestapp E/SQLiteLog: (14) os_unix.c:39583: (2) open(/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge) -
2022-04-21 10:16:05.646 21001-21054/com.adobe.marketing.edgetestapp E/SQLiteDatabase: Failed to open database '/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge': Directory /data/user/0/com.adobe.marketing.edgetestapp/cache doesn't exist
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:254)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:737)
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.openDatabase(SQLiteDatabaseHelper.java:244)
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.query(SQLiteDatabaseHelper.java:105)
        at com.adobe.marketing.mobile.services.SQLiteDataQueue.peek(SQLiteDataQueue.java:94)
        at com.adobe.marketing.mobile.services.SQLiteDataQueue.peek(SQLiteDataQueue.java:124)
        at com.adobe.marketing.mobile.services.PersistentHitQueue$1.run(PersistentHitQueue.java:99)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205) 
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198) 
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919) 
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899) 
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790) 
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:737) 
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.openDatabase(SQLiteDatabaseHelper.java:244) 
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.query(SQLiteDatabaseHelper.java:105) 
        at com.adobe.marketing.mobile.services.SQLiteDataQueue.peek(SQLiteDataQueue.java:94) 
        at com.adobe.marketing.mobile.services.SQLiteDataQueue.peek(SQLiteDataQueue.java:124) 
        at com.adobe.marketing.mobile.services.PersistentHitQueue$1.run(PersistentHitQueue.java:99) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2022-04-21 10:16:05.648 21001-21054/com.adobe.marketing.edgetestapp D/AdobeExperienceSDK: ADBDatabase - query - Error in querying database table (TB_AEP_DATA_ENTITY). Error: (Cannot open database '/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge': Directory /data/user/0/com.adobe.marketing.edgetestapp/cache doesn't exist)
2022-04-21 10:16:05.651 21001-21054/com.adobe.marketing.edgetestapp D/AdobeExperienceSDK: ADBDatabase - closeDatabase - Unable to close database, database passed is null.
2022-04-21 10:16:05.652 21001-21054/com.adobe.marketing.edgetestapp D/AdobeExperienceSDK: SQLiteDataQueue - peek - 0 DataEntities fetch, returning null
2022-04-21 10:16:05.655 21001-21051/com.adobe.marketing.edgetestapp E/SQLiteLog: (14) cannot open file at line 39583 of [bcd014c473]
2022-04-21 10:16:05.657 21001-21051/com.adobe.marketing.edgetestapp E/SQLiteLog: (14) os_unix.c:39583: (2) open(/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge) -
2022-04-21 10:16:05.658 21001-21051/com.adobe.marketing.edgetestapp E/SQLiteDatabase: Failed to open database '/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge': Directory /data/user/0/com.adobe.marketing.edgetestapp/cache doesn't exist
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:254)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:737)
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.openDatabase(SQLiteDatabaseHelper.java:244)
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.insertRow(SQLiteDatabaseHelper.java:80)
        at com.adobe.marketing.mobile.services.SQLiteDataQueue.add(SQLiteDataQueue.java:72)
        at com.adobe.marketing.mobile.services.PersistentHitQueue.queue(PersistentHitQueue.java:49)
        at com.adobe.marketing.mobile.EdgeExtension.processCachedEvents(EdgeExtension.java:358)
        at com.adobe.marketing.mobile.EdgeExtension.processAddEvent(EdgeExtension.java:309)
        at com.adobe.marketing.mobile.EdgeExtension.handleExperienceEventRequest(EdgeExtension.java:269)
        at com.adobe.marketing.mobile.EdgeExtensionListener$2.run(EdgeExtensionListener.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205) 
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198) 
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919) 
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899) 
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790) 
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:737) 
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.openDatabase(SQLiteDatabaseHelper.java:244) 
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.insertRow(SQLiteDatabaseHelper.java:80) 
        at com.adobe.marketing.mobile.services.SQLiteDataQueue.add(SQLiteDataQueue.java:72) 
        at com.adobe.marketing.mobile.services.PersistentHitQueue.queue(PersistentHitQueue.java:49) 
        at com.adobe.marketing.mobile.EdgeExtension.processCachedEvents(EdgeExtension.java:358) 
        at com.adobe.marketing.mobile.EdgeExtension.processAddEvent(EdgeExtension.java:309) 
        at com.adobe.marketing.mobile.EdgeExtension.handleExperienceEventRequest(EdgeExtension.java:269) 
        at com.adobe.marketing.mobile.EdgeExtensionListener$2.run(EdgeExtensionListener.java:74) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2022-04-21 10:16:05.658 21001-21051/com.adobe.marketing.edgetestapp D/AdobeExperienceSDK: ADBDatabase - insertRow - Error in inserting row into table (TB_AEP_DATA_ENTITY). Error: (Cannot open database '/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge': Directory /data/user/0/com.adobe.marketing.edgetestapp/cache doesn't exist)
2022-04-21 10:16:05.659 21001-21051/com.adobe.marketing.edgetestapp D/AdobeExperienceSDK: ADBDatabase - closeDatabase - Unable to close database, database passed is null.
2022-04-21 10:16:05.659 21001-21051/com.adobe.marketing.edgetestapp V/AdobeExperienceSDK: SQLiteDataQueue - add - Successfully added DataEntity (DataEntity{uniqueIdentifier='e1663577-79d3-41c9-aca1-32ff37bc1dc6', timeStamp=Thu Apr 21 10:16:05 PDT 2022, data={"event":{"type":"com.adobe.eventtype.edge","source":"com.adobe.eventsource.requestcontent","number":25,"name":"AEP Request Event","timestamp":1650561365457,"responsePairId":"27d77990-60c5-4534-8445-035277570f72","data":{"xdm":{"eventType":"commerce.purchases","commerce":{"productListAdds":{"value":21},"purchases":{"value":1},"order":{"priceTotal":20,"currencyCode":"RON"}}},"datasetId":"abc"},"uuid":"e1663577-79d3-41c9-aca1-32ff37bc1dc6"},"configuration":{"edge.configId":"example","edge.domain":"example.data.adobedc.net"},"identityMap":{"identityMap":{"ECID":[{"id":"09867831920078526066116478502603050971","authenticatedState":"ambiguous","primary":false}]}}}}) to DataQueue
2022-04-21 10:16:05.660 21001-21054/com.adobe.marketing.edgetestapp E/SQLiteLog: (14) cannot open file at line 39583 of [bcd014c473]
2022-04-21 10:16:05.661 21001-21054/com.adobe.marketing.edgetestapp E/SQLiteLog: (14) os_unix.c:39583: (2) open(/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge) -
2022-04-21 10:16:05.662 21001-21054/com.adobe.marketing.edgetestapp E/SQLiteDatabase: Failed to open database '/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge'.
    android.database.sqlite.SQLiteCantOpenDatabaseException: Cannot open database '/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge': Directory /data/user/0/com.adobe.marketing.edgetestapp/cache doesn't exist
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:254)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:737)
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.openDatabase(SQLiteDatabaseHelper.java:244)
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.query(SQLiteDatabaseHelper.java:105)
        at com.adobe.marketing.mobile.services.SQLiteDataQueue.peek(SQLiteDataQueue.java:94)
        at com.adobe.marketing.mobile.services.SQLiteDataQueue.peek(SQLiteDataQueue.java:124)
        at com.adobe.marketing.mobile.services.PersistentHitQueue$1.run(PersistentHitQueue.java:99)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14 SQLITE_CANTOPEN): Could not open database
        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:224)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:205) 
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:505) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:206) 
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:198) 
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:919) 
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:899) 
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:790) 
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:737) 
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.openDatabase(SQLiteDatabaseHelper.java:244) 
        at com.adobe.marketing.mobile.services.SQLiteDatabaseHelper.query(SQLiteDatabaseHelper.java:105) 
        at com.adobe.marketing.mobile.services.SQLiteDataQueue.peek(SQLiteDataQueue.java:94) 
        at com.adobe.marketing.mobile.services.SQLiteDataQueue.peek(SQLiteDataQueue.java:124) 
        at com.adobe.marketing.mobile.services.PersistentHitQueue$1.run(PersistentHitQueue.java:99) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2022-04-21 10:16:05.662 21001-21054/com.adobe.marketing.edgetestapp D/AdobeExperienceSDK: ADBDatabase - query - Error in querying database table (TB_AEP_DATA_ENTITY). Error: (Cannot open database '/data/user/0/com.adobe.marketing.edgetestapp/cache/com.adobe.edge': Directory /data/user/0/com.adobe.marketing.edgetestapp/cache doesn't exist)
2022-04-21 10:16:05.662 21001-21054/com.adobe.marketing.edgetestapp D/AdobeExperienceSDK: ADBDatabase - closeDatabase - Unable to close database, database passed is null.
2022-04-21 10:16:05.663 21001-21054/com.adobe.marketing.edgetestapp D/AdobeExperienceSDK: SQLiteDataQueue - peek - 0 DataEntities fetch, returning null

</details>

**Comment by praveek** [comment]
With 2.0 changes, we open/close the DB for each operation. This issue is now resolved.
